config/routes.rb
Rails.application.routes.draw do
  resources :users

  post '/auth/:provider/callback', to: 'user_essions#create'
  get '/login', to: 'user_sessions#new'
  post '/login', to: 'user_sessions#create'
  delete '/logout', to: 'user_sessions#destroy'
  get '/partial/_config', to: 'tops#ajax'
  post '/partial/_config', to: 'users#update'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'tops#top'
  post 'ima', to:'tops#ima'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/top.rb
class Top < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  enum region: { japan: 0, UTC: 100 }
  enum full_machine_voice:{ n: 0, y: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :info, :warning, :danger

  def integer_string?(str)
    Integer(str)
    true
  rescue ArgumentError
    false
  end

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def top
  end

  def ima
    t = Time.now
    @ima = t.strftime( "%H時%M分%S秒です" )
  end

  def ajax
    render partial: 'partial/config'
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
# skip_before_action :require_login, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])
    if @user
      redirect_back_or_to root_path, success: 'Login successful.'
    else
      flash.now[:danger] = 'Login failed.'
      render :new
    end
  end

  def destroy
    logout
    redirect_to login_path, success: 'Logout successful.'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to login_path
      flash[:notice] = 'ユーザーの作成に成功しました'
    else
      flash.now[:alert] = 'ユーザーの作成に失敗しました'
      render :root
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(current_user.id)
    if @user.update(user_config)
      redirect_to root_path, success: 'config update'
    else
      flash.now[:danger] = 'config update failured'
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

  def user_config
    params.permit(:region)
  end

  def params_int(user_config)
    user_config.each do |key, value|
      if integer_string?(value)
        user_config[key]=value.to_i
      end
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IMNNGapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/login.html.erb
<%= form_with url: login_path, methof: :post do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password, "password" %>
  <%= f.password_field :password %>
  <%= f.submit 'ログイン' %>
<% end %>

app/views/partial/_config.html.erb
<h1> コンフィグの予定地 </h1>
<%= form_with model: @user do |f| %>
  <%= f.select :region, User.regions.keys.to_a,{} %>
  <%= f.submit '保存' %>
<% end %>

app/views/tops/ima.js.erb
document.getElementById('ima').value = "<%= @ima %>";

app/views/tops/top.html.erb
<br>
<br>
<div class="content">
  <div class="audio", id = "audio">
    <audio id = "sounds" src = "assets/y2mate.com.wav" preload="auto">
    </audio>
    <%= button_to "教えて桑田佳祐！",{action: 'ima'}, {remote: true, class: 'flat border'} %>
  </div>
<br>
  <% if not logged_in? %>
    <%= link_to 'ユーザー作成', new_user_path %>
  <% end %>
<br>
  <% if logged_in? %>
    <%= link_to 'ログアウト', logout_path, method: :delete %>
  <% else %>
    <%= link_to 'ログイン', login_path %>
  <% end %>
</div>
<br>
<br>
<input id='ima' type='hidden'>



<!--<% if logged_in? %>
  <%= button_tag 'コンフィグを設定', type: "button", id: "button1" %>
  <div id="message"></div>
  <div id="button_area"></div>
<%end%> -->





<script>
sounds.addEventListener('ended', function () {
  const text = document.getElementById("ima").value;
  const uttr = new SpeechSynthesisUtterance();
  uttr.text = text;
  window.speechSynthesis.speak(uttr);
});

</script>

app/views/user_sessions/new.html.erb
<%= form_with url: login_path, method: :post do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.submit 'ログイン' %>
<%end%>

app/views/users/new.html.erb
<%= form_with model: @user, local: true do |f| %>
  <%= f.label :email%>
  <%= f.text_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "登録" %>
<%end%>